services:

  # ==========================================
  # MongoDB
  # ==========================================
  mongodb:
    image: mongo:7
    container_name: cryptopulse-mongodb
    restart: unless-stopped

    ports:
      - "27017:27017"

    volumes:
      - mongodb_data:/data/db


  # ==========================================
  # Kafka
  # ==========================================
  kafka:
    image: apache/kafka:4.0.1
    container_name: cryptopulse-kafka
    restart: unless-stopped

    ports:
      - "9092:9092"

    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller

      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093

      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092,EXTERNAL://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093

      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,EXTERNAL://localhost:9092

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT

      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"


  # ==========================================
  # Backend
  # ==========================================
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile

    container_name: cryptopulse-backend
    restart: unless-stopped

    ports:
      - "8000:8000"

    environment:

      # JWT
      ACCESS_TOKEN_EXPIRE_MINUTES: "30"
      SECRET_KEY: cryptopulse_secret_key_2026
      ALGORITHM: HS256

      # Admin
      ADMIN_EMAIL: dharmika@cryptopulse.com
      ADMIN_PASSWORD: Admin@123

      # MongoDB
      MONGO_URI: mongodb://mongodb:27017
      DATABASE_NAME: cryptopulse_db

      # MongoDB Collections
      LIVE_PRICES_COLLECTION: live_prices
      HISTORICAL_PRICES_COLLECTION: historical_prices
      ALERTS_COLLECTION: alerts

      # Kafka
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      KAFKA_TOPIC: crypto-prices

      # Cryptocurrency
      SUPPORTED_COINS: bitcoin,ethereum,solana
      CURRENCY: usd

      # Alerts
      BITCOIN_ALERT_PRICE: "70000"

    depends_on:
      - mongodb
      - kafka


  # ==========================================
  # Frontend
  # ==========================================
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile

    container_name: cryptopulse-frontend
    restart: unless-stopped

    ports:
      - "5173:5173"

    depends_on:
      - backend


# ==========================================
# Volumes
# ==========================================
volumes:
  mongodb_data: